version: "3.1"
services:
  website:
    build:
      context: website
    container_name: ${APP_NAME}_website
#    depends_on:
#      - db
    ports:
      - "${WEBSITE_PORT}:80"
    volumes:
      - ./website:/var/www/project
      - ~/.composer/auth.json:/root/.composer/auth.json 
